# Generated by Django 4.2.6 on 2023-11-08 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_carrera', models.CharField(max_length=20, verbose_name='code')),
                ('nombre', models.CharField(max_length=200, verbose_name='name')),
            ],
            options={
                'verbose_name': 'carrer',
                'verbose_name_plural': 'carrers',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Paralell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('semestre', models.IntegerField(default=1, verbose_name='semestre')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='notas_userPhoto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='notas_teacherPhoto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ('-lastname',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dategraduate', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Graduacion')),
                ('graduate', models.BooleanField(default=False, verbose_name='Graduado')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='notas_studentPhoto')),
                ('carrera', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='notas.carrer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ('-lastname',),
            },
        ),
        migrations.CreateModel(
            name='enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('paralell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notas.paralell')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notas.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='carrer',
            name='Facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.faculty'),
        ),
        migrations.AddField(
            model_name='carrer',
            name='materias',
            field=models.ManyToManyField(to='notas.subject'),
        ),
        migrations.CreateModel(
            name='calification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.IntegerField(default=0, verbose_name='n1')),
                ('n2', models.IntegerField(default=0, verbose_name='n2')),
                ('n3', models.IntegerField(default=0, verbose_name='n3')),
                ('n4', models.IntegerField(default=0, verbose_name='n4')),
                ('ex1', models.IntegerField(default=0, verbose_name='ex1')),
                ('ex2', models.IntegerField(default=0, verbose_name='ex2')),
                ('p1', models.IntegerField(default=0, verbose_name='p1')),
                ('p2', models.IntegerField(default=0, verbose_name='p2')),
                ('re', models.IntegerField(default=0, verbose_name='re')),
                ('final', models.IntegerField(default=0, verbose_name='final')),
                ('enroll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notas.enrollment')),
            ],
        ),
    ]
