# Generated by Django 4.2.6 on 2023-11-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-lastname',), 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='paralell',
            field=models.CharField(max_length=20, verbose_name='paralell'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='studentPhoto/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacherPhoto/'),
        ),
        migrations.DeleteModel(
            name='Paralell',
        ),
    ]
