# Generated by Django 4.2.6 on 2023-11-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_alter_student_options_alter_enrollment_paralell_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='default_photo.png', null=True, upload_to='studentPhoto/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, default='default_photo.png', null=True, upload_to='teacherPhoto/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='default_photo.png', null=True, upload_to='userPhoto/'),
        ),
    ]
