# Generated by Django 4.2.6 on 2023-11-03 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_rename_teachers_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.CreateModel(
            name='carrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_carrera', models.CharField(max_length=20, verbose_name='code')),
                ('nombre', models.CharField(max_length=200, verbose_name='name')),
                ('Facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.faculty')),
            ],
            options={
                'verbose_name': 'carrer',
                'verbose_name_plural': 'carrers',
                'ordering': ('nombre',),
            },
        ),
    ]
