# Generated by Django 4.2.6 on 2023-11-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0007_matricula_notas_paralell_subject_teacher_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='notas_user'),
        ),
    ]
