# Generated by Django 4.2.6 on 2023-11-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0009_alter_student_photo_alter_teacher_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calification',
            name='asistencia',
            field=models.IntegerField(default=0, verbose_name='asistencia'),
        ),
    ]
